#!/usr/bin/env python3
"""Regenerates include/CaBundle.h from certs/*.pem (pinned root CAs for the API host).

Run after changing certs/. CI checks that the header is up to date.
"""
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parent.parent
pems = sorted((root / "certs").glob("*.pem"))
body = "".join(p.read_text().strip() + "\n" for p in pems)
header = (
    "// Generated by scripts/make_ca_bundle.py from certs/*.pem — do not edit.\n"
    "// Pinned roots: " + ", ".join(p.stem for p in pems) + "\n"
    "#pragma once\n\n"
    'static const char kCaBundle[] = R"PEM(\n' + body + ')PEM";\n'
)
out = root / "include" / "CaBundle.h"
if "--check" in sys.argv:
    sys.exit(0 if out.exists() and out.read_text() == header else "include/CaBundle.h is stale: run scripts/make_ca_bundle.py")
out.write_text(header)
print(f"wrote {out} ({len(pems)} certificates)")
